# This is a SecretProviderClass using user-assigned identity to access an Azure Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "spc-github-customized-helm-charts-repo"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.clientId | quote }}
    keyvaultName: {{ .Values.vaultName | quote }}
    tenantId: {{ .Values.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: password
          objectType: secret                     # object types: secret, key or cert
          objectVersion: ""
  secretObjects:  # reflect exposed objects in k8s Secret
    - secretName: github-customized-helm-charts-repo
      type: Opaque
      # labels:
      #   argocd.argoproj.io/secret-type: repository
      data:
        - objectName: password
          key: password