apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: azure-vault1
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.tenantId | quote }}
      vaultUrl: "https://{{ .Values.vaultName }}.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
          namespace: external-secrets