apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
      - secure-nginx.jr-k8s.de
      secretName: quickstart-example-tls
  rules:
    - host: secure-nginx.jr-k8s.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80