apiVersion: v1
kind: Secret
metadata:
  name: argocd-apps-repo
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: argocd-apps
  url: https://github.com/j-reiners/argocd-apps.git
  username: j-reiners
  password: {{ .Values.githubToken }}