apiVersion: v1
kind: Secret
metadata:
  name: "azure-client-credentials"
  namespace: external-secrets
type: Opaque
data:
  # generate 32 chars long random string, base64 encode it and then double-quote the result string.
  ClientID: {{ .Values.clientId | b64enc | quote }}
  ClientSecret: {{ .Values.clientSecret | b64enc | quote }}